apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: docker-service
  namespace: nexus
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8082'
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: docker-push-service
  namespace: nexus
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8083'
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
    - port: 8083
