apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/pv-nexus"
