apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: gitlab
spec:
  serviceName: gitlab
  replicas: 1
  selector:
    matchLabels:
      name: gitlab
  template:
    metadata:
      labels:
        name: gitlab
        app: gitlab
    spec:
      containers:
      - name: gitlab
        #image: sameersbn/gitlab:14.2.4
        image: sameersbn/gitlab:13.3.0
        #imagePullPolicy: Always
        env:
        - name: TZ
          value: Europe/Bucharest
        - name: GITLAB_TIMEZONE
          value: Bucharest
        - name: DEBUG
          value: "true"

        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: P26qS5+Csz50Dkd0DLM2oN9owVBFg0PB
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: KVaMTKLAIElEp0s4L02c1O9JCP0Rfapb
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: nXJJ358Qnci0yF9qpAsLrF2vImaoFR03

        - name: GITLAB_ROOT_PASSWORD
          value: GitlabRootPassword
        - name: GITLAB_ROOT_EMAIL
          value: root@example.com



        # - name: GITLAB_ROOT_PASSWORD
        #   value:
        # - name: GITLAB_ROOT_EMAIL
        #   value:

        - name: GITLAB_HOST
          value: gitlab.sts.com
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_HOST
          value: "gitlab.sts.com"
        - name: GITLAB_SSH_PORT
          value: "22"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00


        #- name: DB_ADAPTER
          #value: postgresql
        - name: DB_HOST
          #value: gitlab-postgresql-0
          value: "10.244.2.38"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: passw0rd
        - name: DB_NAME
          value: gitlab_production


        - name: REDIS_HOST
          value: "10.244.1.95"

        - name: REDIS_PORT
          value: "6379"

        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        securityContext:
          capabilities:
            add:
              - AUDIT_WRITE
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        # livenessProbe:
        #   httpGet:
        #     path: /users/sign_in
        #     port: 80
        #   initialDelaySeconds: 180
        #   timeoutSeconds: 15
        # readinessProbe:
        #   httpGet:
        #     path: /users/sign_in
        #     port: 80
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 1

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-pvc        
