apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: gitlab-vs
spec:
  host: gitlab.sts.com
  tls:
    secret: gitlab-secret
  upstreams:
  - name: home
    service: gitlab-svc
    port: 80
  routes:
  - path: /
    action:
      pass: home
