apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-sock-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: docker-sock-pvc
    namespace: jenkins
  hostPath:
    path: /var/run/docker.sock
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-sock-pvc
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: docker-sock-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
