apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: licenta
spec:
  host: licenta.python.com
  tls:
    secret: licenta-secret
  upstreams:
  - name: home
    service: svc-licenta
    port: 80
  routes:
  - path: /
    action:
      pass: home
